### ISSUE TITLE
Compare with another DSL

### ISSUE THREAD

**Issue by oleksii-demedetskyi** [smileyborg/UIView-AutoLayout#1]
Hi. I am contributor to [Parus lib](https://github.com/DAlOG/Parus), and i want to ask you to review this lib. May be you can find some ideas how to improve your lib. Also, I have thoughts about mixing different Auto-Layout improvement libs under same core with different syntax facades. What do you think on this?

**Comment by smileyborg** [comment]
Do you have some sample code or examples for Parus? Would be great to read through that instead of the API alone.

As far as combining the work of Auto Layout libraries, I think they're different enough to warrant different internals. This is because each project has different design goals and a different approach to the problem. Certainly, if there are specific things from one library missing in another, it's great to leverage the existing work and expose it in the other project (perhaps in that project's own way of doing things).
