### ISSUE TITLE
NSArray of constraints is messy to use

### ISSUE THREAD

**Issue by eoghain** [smileyborg/UIView-AutoLayout#11]
Love your category, I was in the process of building my own when I ran across it.  However, there is one thing that's bothering me and that is returning an NSArray of constraints from your multiple setter methods like [autoPinEdgesToSuperviewEdgesWithInsets:].  With the return of an array I need to walk the array and do some mapping to get ahold of the created constraints, like so:

``` objective-c
NSArray * iconConstraints = [self.iconLabel autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsMake(0, self.bounds.size.width - 87, -5, -3) excludingEdge:ALEdgeTop];
for (NSLayoutConstraint * constraint in iconConstraints)
{
    if (constraint.firstAttribute == NSLayoutAttributeLeading)
    {
        self.iconLeft = constraint;
    }

    if (constraint.firstAttribute == NSLayoutAttributeBottom)
    {
        self.iconBottom = constraint;
    }

    if (constraint.firstAttribute == NSLayoutAttributeTrailing)
    {
        self.iconRight = constraint;
    }
}
```

I've written myself a little helper to do this, but I'd much rather just have the category return the dictionary.

``` objective-c
- (NSDictionary *)dictionaryFromConstraintsArray:(NSArray *)array
{
    NSMutableDictionary * dictionary = [NSMutableDictionary new];

    for (NSLayoutConstraint * constraint in array)
    {
        dictionary[@( constraint.firstAttribute )] = constraint;
    }

    return dictionary;
}
```

So I can call it like so:

``` objective-c
NSDictionary * iconConstraints = [self dictionaryFromConstraintsArray:[self.iconLabel autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsMake(0, self.bounds.size.width - 87, -5, -3) excludingEdge:ALEdgeTop]];
self.iconLeft = iconConstraints[@( ALEdgeLeading )];
self.iconBottom = iconConstraints[@( ALEdgeBottom )];
self.iconRight = iconConstraints[@( ALEdgeTrailing )];
```

I haven't updated your code, and made a pull request for this since it changes your API significantly and wasn't sure how you'd like to approach this.  I'm more than willing to do the work if you can let me know how you think it'd fit best?

**Comment by smileyborg** [comment]
Interesting, can you share your use case for frequently needing to grab references to these constraints?

The "bulk" methods which create multiple constraints return arrays (in fact, these arrays are really more like sets, since the constraints are not ordered) because the expectation is that you may just want to remove all those constraints in one shot later on. If you need a reference to a specific constraint (such as to change its `constant` value), the expectation is that you wouldn't use these "bulk" methods which create multiple constraints (and return an NSArray).

In the numerous Auto Layout implementations I have come across so far, I have found that it's fairly rare to need to hold a reference to a specific constraint, and therefore it's reasonable to have to create/add these specific constraints one at a time.

For example, instead of using:

```
NSArray *constraints = [view autoPinEdgesToSuperviewEdgesWithInsets:UIEdgeInsetsMake(10, 10, 10, 10)];
```

you would do the following if you needed to just hold a reference to the top edge constraint tweak the constant later on:

```
NSLayoutConstraint *constraint = [view autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:10];
[view autoPinEdgeToSuperviewEdge:ALEdgeLeft withInset:10];
[view autoPinEdgeToSuperviewEdge:ALEdgeBottom withInset:10];
[view autoPinEdgeToSuperviewEdge:ALEdgeRight withInset:10];
```

Now, returning a dictionary isn't unreasonable, but consider some of the more complex methods in the category that currently return an array of constraints. For the example you give, it's pretty simple because we're dealing with one view and its superview. But other methods involve arbitrary numbers of views, for example. What would the key be for each constraint? (Note that using the first attribute of the constraint isn't reliable -- constraints can be expressed "backwards" with the attributes flipped and work identically...this is effectively an implementation detail. It's also not scalable for multiple views, etc.)

So anyways, I'm curious about your use case that requires frequently access to individual constraints from within these arrays. If this is a valid and common use case, perhaps there's another way we can solve it.

**Comment by eoghain** [comment]
You have a very valid point.  My use case may not be that common, basically I have a view that I want to place in a given position for one state, and then move it over 20 points in another state. So while I could easily make the 4 calls to set it's edges and only hold onto the edge I want to animate, I was hoping to use the bulk call as it's nice and concise and just grab out my one constraint that i'll animate later.  I guess I just like that using the single call over the multiple when it's just as clear what's going on as the more called out steps.

I agree that my example is a very simplistic setup and doesn't take into account any of your more complex layout helpers.  One of the reasons I didn't just make the changes and issue a pull request.  I didn't want to miss something, or just be going down the wrong path.

While using the first attribute isn't a guarantee, that is only because I'm accessing it from the outside.   I'd assume that if the API was changed to return a dictionary it'd be built to avoid any ambiguity.

``` objc
- (NSDictionary *)autoPinEdgesToSuperviewEdgesWithInsets:(UIEdgeInsets)insets
{
    NSMutableDictionary *constraints = [NSMutableDictionary new];
    constraints[@( ALEdgeTop )] = [self autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:insets.top];
    constraints[@( ALEdgeLeading )] = [self autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:insets.left];
    constraints[@( ALEdgeBottom )] = [self autoPinEdgeToSuperviewEdge:ALEdgeBottom withInset:insets.bottom];
    constraints[@( ALEdgeTrailing )] = [self autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:insets.right];
    return constraints;
}
```

Anyway feel free to close this if you don't see any merit to the change.  I can use the more explicit way of setting each edge so as to avoid a possible issue with the constraint being expressed "backwards".

**Comment by smileyborg** [comment]
Got it, thanks for the explanation. It sounds like even for you this is a somewhat infrequent use case. Designing complete API like this is somewhat of a balancing act between making sure it works well for most use cases, and keeping it as slim as possible. It's always easy to get caught up adding new things and before you know it, you have a bloated interface that is more complicated than it should be.

For the sake of not introducing a whole new set of methods with different return types, or making any breaking changes to the existing API, I'd rather leave things as they currently are. For now, I think this sort of thing falls into what I consider the "client's burden" -- you can definitely feel free to create your own category that adds some additional helpers/extensions, which could even wrap calls to the UIView+AutoLayout category and do whatever additional work is needed to keep your client code clean.

Anyways, thanks for bringing this up -- always happy to hear about potential improvements and new use cases!
