### ISSUE TITLE
initForAutoLayout

### ISSUE THREAD

**Issue by tcurdt** [smileyborg/UIView-AutoLayout#15]
...should use `initWithFrame:CGRectZero` over a plain `init`. It's not exactly the standard way of creating views like that and many views don't deal with it very well.

**Comment by smileyborg** [comment]
Yes, you are correct in that `initWithFrame:` is the designated initializer for a UIView class. However, in my experience, calling `init` is functionally identical (in fact, I think I remember observing that UIView's `init` just calls `[self initWithFrame:CGRectZero]`).

I'm not opposed to changing this, but the reason it's written with `init` is because specifying a starting frame is unnecessary and doesn't really make sense with auto layout.

Can you share some examples of specific cases you have found where using `+[new]` or `-[init]` didn't work correctly?

**Comment by tcurdt** [comment]
Totally get where you are coming from - and I just checked. Indeed `init` is calling `[self initWithFrame:CGRectZero]` ...hence I must have misdiagnosed the original problem I had. (I am a little puzzled what the problem was then. Odd. Anyway!)

So I guess we could just close this issue but... given that `initWithFrame:` is the designated initializer and UIView is doing the same thing - why not do the obvious thing? After all it's an implementation detail that is hidden anyway in `initForAutoLayout`. It would be a little clearer and it would save one selector call - not that the latter really matters that much ;)

Anyway - up to you. I will raise an issue if I run into it again. But if it was me - I would change it to directly call the designated initializer.

**Comment by smileyborg** [comment]
One argument in favor of leaving it as `init` is that's exactly what `[UIView newAutoLayoutView]` will end up doing as well. This really only matters for subclasses of UIView, where I could see someone creating their own subclass and only overriding `init` (instead of `initWithFrame:`) because they intended the class to be used with auto layout and weren't thinking about using frames at all. Of course, they **should** be also overriding `initWithFrame:` and making sure to call `super`, but if this was omitted, the current code would at least run their code.

**Comment by smileyborg** [comment]
Let's leave it as is for now. I'm more than happy to change it if there is a compelling argument to do so though.
