### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by LewisLauYang** [smileyborg/UIView-AutoLayout#20]
viewcontroller use UIView-AutoLayout,when pop from Navigationcontroller,viewcontroller never call dealloc. is UIView-AutoLayout's bug?

**Comment by smileyborg** [comment]
First of all, UIView+AutoLayout has been deprecated. It is no longer being updated or supported, you should switch to using [PureLayout](https://github.com/smileyborg/PureLayout).

As far as memory leaks, I have not observed any, and the library is used by many other developers who have not reported any issues. What has led you to believe that the issue is UIView+AutoLayout?

**Comment by ghost** [comment]
Tyler is right. It's very unlikely that there are memory leaks caused by
UIView+AutoLayout.

I would recommend that you review your UITableViewDelegate and
UITableViewDataSource implementations. You are probably forcing a cell
dequeue and not using/returning them. So the system can't access them in
order to manage memory properly.

I can provide you more details if you need. I had similar issues before,
but they were all about my implementation.

2014-09-26 10:25 GMT-03:00 Tyler Fox notifications@github.com:
